server:
  port: 9000

spring:
  application:
    name: sc-gateway

  cloud:
    gateway:
      routes:
        - id: hello_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8765 # 타겟 서비스의 URI
          predicates:
            - Path=/hello # 매칭할 경로 (정확히 /hello)

          # abc2hello_route
          # 1. http://localhost:9000/hello 로 들어오면
          # 2. http://localhost:8765/hello 로 연결

        - id: abc2hello_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8765 # 타겟 서비스의 URI
          predicates:
            - Path=/abc

          # abc2hello_route
          # 1. http://localhost:9000/abc 로 들어오면
          # 2. http://localhost:8765/abc 로 연결

        - id: def2hello_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8765 # 타겟 서비스의 URI
          predicates:
            - Path=/def
          filters:
            - RewritePath=/def, /hello

          # def2hello_route
          # 1. http://localhost:9000/def 로 들어오면
          # 2. 필터에서 def 를 hello 로 바꾸어서 설정된 uri 로 보냄
          # 3. http://localhost:8765/hello 로 연결
